// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BreathNDrinkClassLibrary.Models
{
    public partial class Ratings
    {
        public int RatingId { get; set; }
        public int DrinkId { get; set; }
        public int RatingValue { get; set; }
        public int DrinkerId { get; set; }
    }
}